# Generated by Django 5.0.6 on 2024-05-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
